# Generated by Django 5.0.4 on 2024-10-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_alter_ficha_imagen_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosComunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comio', models.BooleanField(default=False)),
                ('paseo', models.BooleanField(default=False)),
                ('entretencion', models.BooleanField(default=False)),
                ('medicamentos', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.ficha')),
            ],
        ),
    ]
