# Generated by Django 5.0.4 on 2024-10-29 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_servicioscomunes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioscomunes',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_comunes', to='Usuario.ficha'),
        ),
    ]
