# Generated by Django 5.0.4 on 2024-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0001_initial'),
        ('Usuario', '0006_alter_servicioscomunes_ficha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservaservicio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='reservaservicio',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelada', False)), fields=('colaborador', 'servicio', 'fecha_reservada', 'hora_inicio', 'hora_fin'), name='unique_reserva_activa'),
        ),
    ]
