# Generated by Django 5.0.4 on 2024-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_reservaservicio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioscomunes',
            name='dia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicioscomunes',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
