# Generated by Django 5.0.4 on 2024-10-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_regalia'),
        ('Usuario', '0008_servicioscomunes_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioscomunes',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_comunes', to='Producto.reserva'),
        ),
        migrations.AlterField(
            model_name='servicioscomunes',
            name='dia',
            field=models.PositiveIntegerField(),
        ),
    ]
