# Generated by Django 5.0.4 on 2024-11-08 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_regalia'),
        ('Usuario', '0012_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='nombre_sala',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Producto.reserva'),
            preserve_default=False,
        ),
    ]
