# Generated by Django 5.0.4 on 2024-11-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_regalia'),
        ('Usuario', '0013_remove_mensaje_nombre_sala_alter_mensaje_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.reserva'),
        ),
    ]
