# Generated by Django 5.0.4 on 2024-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0014_alter_mensaje_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
