# Generated by Django 5.0.4 on 2024-11-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0014_remove_reserva_trabajador'),
        ('Usuario', '0015_mensaje_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Producto.reserva'),
        ),
    ]
