# Generated by Django 5.1.1 on 2024-11-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0023_remove_reservaregalia_reserva'),
        ('Usuario', '0016_alter_mensaje_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioscomunes',
            name='regalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.reservaregalia'),
        ),
        migrations.AddField(
            model_name='servicioscomunes',
            name='regalo_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/regalo/'),
        ),
    ]
