# Generated by Django 5.1.1 on 2024-11-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0017_servicioscomunes_regalo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioscomunes',
            name='regalo',
        ),
    ]
