# Generated by Django 5.1 on 2024-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0018_remove_servicioscomunes_regalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
