"""
Django settings for proyecto_web project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from os.path import join
from datetime import timedelta
import os
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#e7&&_z6rfz7b5o0zgvs$m8(=thtt1c@3(21*dol=0yhmz^dq+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modulo.Producto.apps.ProductoConfig',
    'modulo.Usuario.apps.UsuarioConfig',
    'modulo.Compra.apps.CompraConfig',
    'modulo.principio.apps.PrincipioConfig',
    'modulo.Colaborador.apps.ColaboradorConfig',
    'sweetify',
    'crispy_forms',
    'crispy_bootstrap5', 
    'django.contrib.humanize',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters',
    

]



CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'proyecto_web.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'proyecto_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR,'template')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_web.wsgi.application'

LOGIN_URL = 'iniciarsesionColaborador'  # O el nombre que uses para la vista de login de colaboradores

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'petsteam',#cambiar segun base de datos de mysql
        'USER':'root', #cambiar segun configuracion mysql
        'PASSWORD':'root',#cambiar segun configuracion mysql
        'HOST':'localhost',
        'PORT': 3306 #cambiar segun configuracion mysql
    }
}

# Correo electronico

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'petsteamcl@gmail.com'
EMAIL_HOST_PASSWORD = 'rfmv itgh wwuu byya'  # Reemplaza por la contraseña real o usa un App Password.



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Configuraciòn de media

# Media files (Uploaded files like images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOAD DEFAULT DATA
FIXTURE_DIRS = [
    join(BASE_DIR, 'fixtures')
]
# Configuraciòn de sweetalert
SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'



MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}





# settings.py

# Modo de operación de Transbank (True para pruebas, False para producción)
TRANSBANK_IS_TEST = True

# Configuraciones de Webpay Plus
# settings.py

# Configuraciones de Webpay Plus
# settings.py
WEBPAY_PLUS_COMMERCE_CODE = '597055555532'
WEBPAY_PLUS_API_KEY = '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
WEBPAY_PLUS_RETURN_URL = 'http://localhost:8000/pagos/confirmar/'


LOGIN_URL = '/iniciarsesion/' 


PDFKIT_WKHTMLTOPDF = os.path.join('ruta/a/wkhtmltopdf')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365 * 100),  # Aproximadamente 100 años
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365 * 100),  # Igual que el token de acceso
}

CORS_ALLOW_ALL_ORIGINS = True #cambiar en produccion

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8100',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)