# Generated by Django 5.1 on 2024-10-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.ficha'),
        ),
    ]
