# Generated by Django 5.1.1 on 2024-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
