# Generated by Django 5.0.4 on 2024-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_reserva_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
