# Generated by Django 5.0.4 on 2024-11-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_reserva_trabajador_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.PositiveBigIntegerField(),
        ),
    ]
