# Generated by Django 5.1 on 2024-11-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaRegalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Regalías')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('regalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_regalia', to='Producto.regalia')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias_reserva', to='Producto.reserva')),
            ],
        ),
    ]
