# Generated by Django 5.1 on 2024-11-12 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_reservaregalia'),
        ('Usuario', '0015_mensaje_leido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegaliaPorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias_compradas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias_compradas', to='Usuario.ficha')),
                ('regalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Producto.regalia')),
            ],
        ),
    ]
