# Generated by Django 5.1 on 2024-11-12 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_regaliaporusuario'),
        ('Usuario', '0015_mensaje_leido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regaliaporusuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regaliaporusuario',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias_mascota', to='Usuario.ficha'),
        ),
        migrations.AlterField(
            model_name='regaliaporusuario',
            name='regalia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalias', to='Producto.regalia'),
        ),
    ]
