# Generated by Django 5.1 on 2024-11-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0011_alter_regaliaporusuario_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegaliaPorUsuario',
        ),
    ]
