# Generated by Django 5.0.4 on 2024-11-19 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_delete_regaliaporusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaregalia',
            old_name='fecha_agregada',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='reservaregalia',
            name='reserva',
        ),
        migrations.AddField(
            model_name='reservaregalia',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaregalia',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservaregalia',
            name='precio_total_r',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
