# Generated by Django 5.1 on 2024-11-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0015_reserva_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
