# Generated by Django 5.1.1 on 2024-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0017_remove_habitacion_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaregalia',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
