# Generated by Django 5.1.1 on 2024-11-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0018_alter_reservaregalia_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaregalia',
            name='pagada',
        ),
    ]
