# Generated by Django 5.1.1 on 2024-11-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0019_remove_reservaregalia_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaregalia',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
