# Generated by Django 5.0.4 on 2024-11-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0020_reservaregalia_pagada'),
        ('Usuario', '0016_alter_mensaje_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_video', models.FileField(upload_to='videos_clientes/', verbose_name='Archivo de Video')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Usuario.usuario')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_mascota', to='Usuario.ficha')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_reserva', to='Producto.reserva')),
            ],
        ),
    ]
