# Generated by Django 5.1.1 on 2024-11-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0021_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaregalia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Producto.reserva'),
        ),
    ]
