# Generated by Django 5.1.1 on 2024-11-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0022_reservaregalia_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaregalia',
            name='reserva',
        ),
    ]
