# Generated by Django 5.1 on 2024-12-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0023_remove_reservaregalia_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaregalia',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regalias', to='Producto.reserva'),
        ),
    ]
