# Generated by Django 5.1 on 2024-12-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0026_alter_reservaregalia_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaregalia',
            name='reserva',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regalias', to='Producto.reserva'),
        ),
    ]
