# Generated by Django 5.1 on 2024-10-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0002_colaborador_precio_por_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
