# Generated by Django 4.0.5 on 2022-06-28 22:43

from django.db import migrations, models
import django.db.models.deletion
import modulo.Producto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc_descuento', models.PositiveSmallIntegerField()),
                ('f_inicio', models.DateField()),
                ('f_termino', models.DateField()),
                ('nombre', models.CharField(default='o', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default=0, upload_to=modulo.Producto.models.generar_nombre_unico)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('id_Promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.promocion')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria')),
            ],
        ),
    ]
