# Generated by Django 5.1 on 2024-10-07 17:50

import django.db.models.deletion
import modulo.Producto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_habitacion', models.FileField(default=0, upload_to=modulo.Producto.models.generar_nombre_unico)),
                ('numero_habitacion', models.CharField(max_length=10, unique=True)),
                ('tipo_habitacion', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.habitacion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.ficha')),
            ],
        ),
    ]
