# Generated by Django 5.1 on 2024-10-05 19:58

import modulo.Producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_habitacion', models.FileField(default=0, upload_to=modulo.Producto.models.generar_nombre_unico)),
                ('numero_habitacion', models.CharField(max_length=10)),
                ('tipo_habitacion', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
