# Generated by Django 5.1 on 2024-08-27 19:15

import django.db.models.deletion
import modulo.Producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_Promocion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default=0, upload_to=modulo.Producto.models.generar_nombre_unico)),
                ('tipoPerro', models.CharField(max_length=200)),
                ('kilos', models.CharField(max_length=200)),
                ('servicio', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
                ('tiempoText', models.CharField(max_length=200)),
                ('id_Promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.promocion')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria')),
            ],
        ),
    ]
