# Generated by Django 5.1 on 2024-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
