# Generated by Django 4.0.5 on 2022-06-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '__first__'),
        ('Usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_compra', models.DateField(auto_now=True)),
                ('Hora_compra', models.DateTimeField(auto_now=True)),
                ('Total_a_pagar', models.PositiveIntegerField()),
                ('cantidad_total', models.PositiveIntegerField()),
                ('id_Estado_compra', models.CharField(choices=[('EP', 'Preparacion'), ('EE', 'Enviado'), ('EF', 'Finlaizado')], default='EP', max_length=2)),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('estado_compra', models.CharField(default='En proceso', max_length=10)),
                ('idHistorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.historial')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Total', models.PositiveIntegerField()),
                ('id_Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
