# Generated by Django 5.1 on 2024-10-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.habitacion')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_compra', models.DateField(auto_now=True)),
                ('Hora_compra', models.DateTimeField(auto_now=True)),
                ('Total_a_pagar', models.PositiveIntegerField()),
                ('cantidad_total', models.PositiveIntegerField()),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('Total', models.PositiveIntegerField()),
                ('id_Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('estado_compra', models.CharField(default='En proceso', max_length=10)),
                ('idHistorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.historial')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('estado_compra', models.CharField(default='En proceso', max_length=10)),
                ('idSeguimiento', models.CharField(choices=[('EP', 'Preparacion'), ('EE', 'Enviado'), ('EF', 'Finalizado')], default='EP', max_length=2)),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
            ],
        ),
    ]
