# Generated by Django 4.0.5 on 2022-06-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('estado_compra', models.CharField(default='En proceso', max_length=10)),
                ('idSeguimiento', models.CharField(choices=[('EP', 'Preparacion'), ('EE', 'Enviado'), ('EF', 'Finalizado')], default='EP', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Estado_compra',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='id_Estado_compra',
        ),
        migrations.AddField(
            model_name='seguimiento2',
            name='idCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra'),
        ),
    ]
