# Generated by Django 5.1 on 2024-08-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0002_seguimiento2_delete_estado_compra_and_more'),
        ('Producto', '0002_remove_producto_id_promocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.habitacion'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='id_Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.habitacion'),
        ),
    ]
