# Generated by Django 5.1 on 2024-10-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0002_colaborador_precio_por_hora'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('fecha_reservada', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colaborador.colaborador')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.ficha')),
            ],
            options={
                'unique_together': {('colaborador', 'servicio', 'fecha_reservada', 'mascota')},
            },
        ),
    ]
