# Generated by Django 5.1 on 2024-10-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='imagen_mascota',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
