# Generated by Django 5.1 on 2024-10-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_reservaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
