# Generated by Django 5.1 on 2024-09-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_fichamascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perro', models.CharField(max_length=100)),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('chip', models.CharField(max_length=10)),
                ('comida', models.CharField(max_length=100)),
                ('vacunas', models.TextField()),
                ('alergias', models.TextField()),
                ('enfermedades', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='FichaMascota',
        ),
    ]
