# Generated by Django 5.0.4 on 2024-10-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='password',
        ),
    ]
