# Generated by Django 5.1 on 2024-10-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_ficha_imagen_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen_mascota',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
