# Generated by Django 4.1.7 on 2024-10-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_remove_colaborador_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perro', models.CharField(max_length=100)),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('chip', models.CharField(max_length=10)),
                ('comida', models.CharField(max_length=100)),
                ('vacunas', models.TextField()),
                ('alergias', models.TextField()),
                ('enfermedades', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
