# Generated by Django 5.1 on 2024-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_reservaservicio_hora_fin_reservaservicio_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
