# Generated by Django 5.1 on 2024-09-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_ficha_delete_fichamascota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ficha',
            new_name='FichaMascota',
        ),
    ]
