# Generated by Django 5.0.4 on 2024-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='password',
            field=models.CharField(default='Matias', max_length=255),
            preserve_default=False,
        ),
    ]
