# Generated by Django 5.1 on 2024-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_rename_ficha_fichamascota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FichaMascota',
            new_name='Ficha',
        ),
    ]
