# Generated by Django 5.1 on 2024-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_rename_fichamascota_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_cuenta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='colaborador',
            field=models.BooleanField(default=False),
        ),
    ]
