# Generated by Django 5.0.4 on 2024-10-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0003_disponibilidad_disponible'),
        ('Usuario', '0005_usuario_direccion_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservaservicio',
            unique_together={('colaborador', 'servicio', 'fecha_reservada', 'hora_inicio', 'hora_fin', 'mascota')},
        ),
    ]
