# Generated by Django 5.0.4 on 2024-10-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_colaborador_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.colaborador')),
            ],
            options={
                'unique_together': {('colaborador', 'servicio', 'fecha', 'hora_inicio')},
            },
        ),
    ]
