# Generated by Django 5.0.4 on 2024-10-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
