# Generated by Django 5.0.4 on 2024-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='estrellas',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Estrellas'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')]),
        ),
    ]
