# Generated by Django 5.0.4 on 2024-10-18 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_alter_calificacion_estrellas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='estrellas',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='foto',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
